const {Enum} = require('./tools')
test('enum', () => {
  const t1 = Enum(['a=5','b=0','c'])
  expect(t1.a).toBe(5)
  expect(t1.b).toBe(0)
  expect(t1.c).toBe(1)
  expect(t1[5]).toBe('a')
  expect(t1[0]).toBe('b')
  expect(t1[1]).toBe('c')
})